# Generated by Django 5.2.8 on 2025-11-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_email', models.CharField(max_length=100)),
                ('seller_contact', models.CharField(max_length=15)),
                ('seller_address', models.CharField(max_length=200)),
                ('seller_photo', models.FileField(upload_to='Assets/SellerDocs/')),
                ('seler_proof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('seller_password', models.CharField(max_length=100)),
                ('seller_status', models.IntegerField(default=0)),
                ('seller_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_address', models.CharField(max_length=200)),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('user_password', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
