# Generated by Django 5.2.8 on 2025-11-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_seller',
            old_name='seler_proof',
            new_name='seller_proof',
        ),
    ]
