# Generated by Django 5.2.8 on 2025-12-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='product',
        ),
    ]
