# Generated by Django 5.2.8 on 2025-12-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_tbl_booking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='cart_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
