# Generated by Django 5.2.8 on 2025-12-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_tbl_cart_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.CharField(null=True),
        ),
    ]
