# Generated by Django 5.2.8 on 2025-12-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
